### ISSUE TITLE
The site is not available over HTTPS.

### ISSUE THREAD

**Issue by teo-tsirpanis** [zyanfx/Zyan.com.de#2]
HTTPS is necessary for security and performance even on static sites. If the site is hosted on GitHub Pages [this guide](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https) can help you to enable it.

**Comment by yallie** [comment]
Hi @teo-tsirpanis,

thanks for pointing it out, and also thanks for your submitted changes!
The site is actually hosted at https://zyan.sslk.ru/ with https enabled.
Zyan.com.de is a some kind of a wrapper for the actual website.

@theRainbird, do you still have the control over zyan.com.de?
Could you please enable https protocol for this domain? :)

**Comment by theRainbird** [comment]
Hi yallie,

I've switched web forwarding to https. 
All calls (regardless if http or https) on zyan.com.de are now forwarded to https://zyan.sslk.ru/.

**Comment by yallie** [comment]
Hi @theRainbird, that's great, thanks!

Does it currently work for you?
I don't seem to be able to open https://zyan.com.de
Perhaps it needs some time to refresh the DNS records.

UPD. Cool, I see now it works.
